#greeting:
#  message: Welcome to the Simple E-commerce.

# Env for RestTemplate & Error Decoder
#order_service:
#  url: http://ORDER-SERVICE/order-service/%s/orders
#  exception:
#    orders_is_empty: There is no item.