server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true # periodically get recent information from eureka server
    service-url: # register itself to eureka server end point
      defaultZone: http://localhost:8761/eureka
