server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C:\GitRepo\native-file-repo
        git:
#          uri: file://C:\GitRepo\git-local-repo
          uri: https://github.com/quaternion12345/spring-cloud-config.git
          defaultLabel: master
#          username: [id]
#          password: [password]